version: "3.9"

services:
  db:
    image: postgres:16-bullseye
    env_file: 
      - .env
    ports:
      - "5432:5432"
    networks:
      - api-network
  api:
    build: .
    env_file: 
      - .env
    command: bash -c "pip install --default 1000 -r requirements.txt && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --workers 5 --proxy-headers --reload"
    restart: on-failure
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
    links:
      - db:db
    networks:
      - api-network
  redis:
    image: library/redis:5.0-alpine
    restart: unless-stopped
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
  