# Generated by Django 4.2.5 on 2023-11-29 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_rename_issue_date_customerdocument_date_of_issue_and_more'),
        ('order', '0002_statistics_transaction_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.websites'),
        ),
    ]
