# Generated by Django 4.2.5 on 2023-12-05 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_traders_options'),
        ('order', '0004_alter_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trader', to='customer.customer'),
        ),
    ]
