# Generated by Django 4.2.5 on 2023-12-05 08:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_traderpaymentmethod_options_and_more'),
        ('order', '0005_alter_order_trader'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.traderpaymentmethod'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.CharField(auto_created=uuid.UUID('1a10f4e1-8362-412e-abb5-4b239205c1ca'), default='0604e230-d890-4587-9a7c-7e5150cac94e'),
            preserve_default=False,
        ),
    ]
