# Generated by Django 4.2.5 on 2023-12-05 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_traderpaymentmethod_options_and_more'),
        ('order', '0007_alter_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.traderpaymentmethod'),
        ),
    ]
