# Generated by Django 4.2.5 on 2023-12-07 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_exchangedirection_options'),
        ('order', '0008_alter_order_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='initials',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_details',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.paymentmethods'),
        ),
        migrations.AddField(
            model_name='order',
            name='side',
            field=models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], default='IN', max_length=4),
            preserve_default=False,
        ),
    ]
