# Generated by Django 4.2.5 on 2023-12-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_client_id_order_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(0, 'Deposit'), (1, 'Withdrawal'), (2, 'Client order'), (3, 'Repay'), (4, 'Input order'), (5, 'Output order'), (6, 'Commission')]),
        ),
    ]
