# Generated by Django 4.2.5 on 2023-12-20 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_alter_cards_currency_alter_cards_initials_and_more'),
        ('order', '0012_alter_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='initials',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_details',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='order',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.cards'),
        ),
    ]
