# Generated by Django 4.2.5 on 2023-12-22 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_links_method_alter_links_network'),
        ('order', '0013_remove_order_initials_remove_order_payment_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.paymentmethods'),
        ),
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='initials',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
