from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('transactions/', transactions_view, name='transactions'),
    path('orders/', orders_view, name='orders'),
    path('withdrawals/', withdrawals_view, name='withdrawals'),
    path('cards/', cards, name='cards'),
    path('card/<int:card_id>/', card, name='card'),
    path('update-direction/', update_direction, name='update_direction'),
    path('directions/', payment_methods, name='directions'),
    path('settings/', settings, name='settings'),
    path('support/', support, name='support'),
    path('ticket/<int:ticket_id>/', ticket, name='ticket'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('login/2fa/', login_2fa, name='2fa'),
    path('login/verify-email/', verify_email, name='verify-email'),
    path('signup/trader/', step1, name='step1'),
    path('signup/trader/2/', step2, name='step2'),
    path('signup/trader/3/', step3, name='step3'),
    path('signup/trader/4/', step4, name='step4'),
    path('signup/merchant/', merchant1, name='merchant1'),
    path('request/merchant/', merchant_request, name='request'),
    path('disable-2fa/', disable_2fa, name='disable-2fa'),
    path('change-password/', change_pas, name='change-password'),
    path('reset-password/', reset1, name='reset1'),
    path('reset-password/2/', reset2, name='reset2'),
    path('reset-password/3/', reset3, name='reset3'),
    path('send_email_otp/', send_otp_email, name='send_email_otp'),
    path('send_phone_otp/', send_otp_telegram, name='send_phone_otp'),
    path('deposit/', deposit, name='deposit'),
    path('withdrawal/', withdrawals, name='withdrawal'),
    path('success/', success, name='success'),
    path('order/start/', order_start, name='order-start'),
    path('order/pay/', order, name='order-pay')
]
