# Generated by Django 4.2.5 on 2023-11-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_ticketmessage_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads', verbose_name='message_attachment'),
        ),
    ]
