# Generated by Django 4.2.5 on 2023-12-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_ticketmessage_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Solving'), (2, 'Solved')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='Не работает', max_length=128),
            preserve_default=False,
        ),
    ]
