# Generated by Django 4.2.5 on 2023-12-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='message_attachment'),
        ),
    ]
