# Generated by Django 4.2.5 on 2023-11-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_websites_merchant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchants',
            fields=[
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customer.customer',),
        ),
        migrations.CreateModel(
            name='Traders',
            fields=[
            ],
            options={
                'verbose_name': 'Trader',
                'verbose_name_plural': 'Traderss',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customer.customer',),
        ),
    ]
