# Generated by Django 4.2.5 on 2023-11-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_merchants_traders'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='interest_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ACTIVE', 'Active'), ('Inactive', 'INACTIVE')], max_length=256),
        ),
        migrations.AlterField(
            model_name='websites',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Active'), (2, 'Rejected'), (3, 'Blocked')]),
        ),
        migrations.AlterField(
            model_name='websites',
            name='verified',
            field=models.IntegerField(choices=[(0, 'Verification pending'), (1, 'Verified'), (2, 'Not verified'), (3, 'Verification rejected')]),
        ),
    ]
