# Generated by Django 4.2.5 on 2023-11-29 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_interest_rate_customer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdocument',
            old_name='issue_date',
            new_name='date_of_issue',
        ),
        migrations.RenameField(
            model_name='customerdocument',
            old_name='document_number',
            new_name='passport_number',
        ),
        migrations.RenameField(
            model_name='customerdocument',
            old_name='file',
            new_name='passport_scan',
        ),
        migrations.RemoveField(
            model_name='customerdocument',
            name='data',
        ),
        migrations.RemoveField(
            model_name='customerdocument',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='customerdocument',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customerdocument',
            name='type',
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='authority',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='passport_video',
            field=models.FileField(blank=True, upload_to='videos'),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='status',
            field=models.CharField(choices=[('request', 'Verification request'), ('pending', 'Verification pending'), ('verified', 'Verified'), ('rejected', 'Verification rejected')], default='request', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
