# Generated by Django 4.2.5 on 2023-11-29 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_rename_issue_date_customerdocument_date_of_issue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('site', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=256)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Paused'), (2, 'Approved'), (3, 'Rejected')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'db_table': 'request',
                'ordering': ('created', 'status'),
            },
        ),
        migrations.AlterField(
            model_name='invitecodes',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.request'),
        ),
    ]
