# Generated by Django 4.2.5 on 2023-12-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_traderpaymentmethod_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
