# Generated by Django 4.2.5 on 2023-12-07 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_customer_telegram_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdocument',
            old_name='passport_scan',
            new_name='passport_scan_1',
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='passport_scan_2',
            field=models.FileField(blank=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='traderpaymentmethod',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.traders'),
        ),
    ]
