# Generated by Django 4.2.5 on 2023-12-09 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_customer_telegram_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='telegram_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
