# Generated by Django 4.2.5 on 2023-12-09 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_remove_customer_telegram_name_customer_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
