# Generated by Django 4.2.5 on 2023-12-09 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_request_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='expiry',
        ),
        migrations.AddField(
            model_name='invitecodes',
            name='expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
