# Generated by Django 4.2.5 on 2023-12-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_admin_remove_customer_email_remove_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
