# Generated by Django 4.2.5 on 2023-12-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_remove_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader_deposit_limit', models.IntegerField(verbose_name='Депозит трейдер (лимит)')),
                ('trader_orders', models.IntegerField(verbose_name='Кол-во заявок трейдера на вывод в сутки')),
                ('min_limit', models.IntegerField(verbose_name='Лимит трейдера на минимальную сумму вывода')),
                ('fix_commission', models.IntegerField(verbose_name='Фикс % трейдер')),
                ('merchant_deposit', models.IntegerField(verbose_name='Депозит мерчант (лимит)')),
                ('commission_in', models.IntegerField(verbose_name='Комиссия системы инвойс клиентам')),
                ('commission_out', models.IntegerField(verbose_name='Комиссия системы вывод')),
                ('withdrawals_limit', models.IntegerField(verbose_name='Кол-во заявок мерчанта на вывод в сутки')),
                ('withdrawal_min', models.IntegerField(verbose_name='Лимит мерчанта на минимальную сумму вывода')),
                ('new_merchants_limit', models.IntegerField(verbose_name='Лимиты для новых мерчантов')),
                ('order_life', models.IntegerField(verbose_name='Срок действия ордера (для клиента)')),
                ('max_registration_tries', models.IntegerField(verbose_name='Кол-во попыток ввода кода подтверждения')),
                ('withdrawal_block', models.IntegerField(verbose_name='Блок на вывод средств после смены email/телефон')),
                ('phone_restriction', models.IntegerField(verbose_name='Запрет на использование “освобожденного телефона/email')),
                ('max_ip_requests', models.IntegerField(verbose_name='Кол-во запросов с одного ip')),
                ('max_phone_retries', models.IntegerField(verbose_name='Кол-во регистраций с одного телефона')),
                ('invite_expiration', models.IntegerField(verbose_name='Срок действия инвайт кода')),
                ('website_verification', models.BooleanField(verbose_name='Обязательность верификации сайта мерчанта')),
                ('dns_salt', models.BooleanField(verbose_name='Соль для кода верификации для TXT в DNS ')),
                ('min_traders', models.IntegerField(verbose_name='Минимальное количество активных трейдеров')),
                ('min_amounts', models.IntegerField(verbose_name='Минимальные остатки по лимитам активных трейдеров (в USDT)')),
                ('max_limit', models.IntegerField(verbose_name='Максимальный процент отношения общей суммы заявок за последние 10 минут к остаткам по лимитам всех активных трейдеров (в %)')),
                ('logout_in', models.IntegerField(verbose_name='Разлогинивать через')),
                ('trader_inactive_push', models.IntegerField(verbose_name='Пуш уведомление о “засыпании” трейдера')),
                ('inactive_email', models.IntegerField(verbose_name='Email уведомление о неактивности')),
            ],
        ),
    ]
