# Generated by Django 4.2.5 on 2023-12-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='dns_salt',
            field=models.CharField(verbose_name='Соль для кода верификации для TXT в DNS '),
        ),
    ]
