# Generated by Django 4.2.5 on 2023-12-16 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_links_method_alter_links_network'),
        ('customer', '0024_alter_settings_dns_salt'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderExchangeDirections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.BooleanField()),
                ('output', models.BooleanField()),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.exchangedirection')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.traders')),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('payment_details', models.CharField(max_length=256)),
                ('initials', models.CharField(max_length=256)),
                ('status', models.BooleanField()),
                ('input_operation_limit', models.IntegerField()),
                ('input_day_limit', models.IntegerField()),
                ('input_month_limit', models.IntegerField()),
                ('output_operation_limit', models.IntegerField()),
                ('output_dat_limit', models.IntegerField()),
                ('output_month_limit', models.IntegerField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.traders')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.paymentmethods')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'db_table': 'customer_cards',
            },
        ),
    ]
