# Generated by Django 4.2.5 on 2023-12-20 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_links_method_alter_links_network'),
        ('customer', '0026_remove_cards_input_day_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='initials',
            field=models.CharField(max_length=256, verbose_name='Инициалы владельца карты'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.paymentmethods', verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Никнейм карты'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='payment_details',
            field=models.CharField(max_length=256, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='status',
            field=models.BooleanField(verbose_name='Карта активна'),
        ),
    ]
