# Generated by Django 4.2.5 on 2023-12-22 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_alter_cards_currency_alter_cards_initials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='last_used',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
