# Generated by Django 4.2.5 on 2023-12-22 19:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_cards_last_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='key',
            field=models.CharField(auto_created=uuid.uuid4, default=uuid.uuid4, max_length=128),
        ),
    ]
