# Generated by Django 4.2.5 on 2023-12-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_websites_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='personal_course',
            field=models.FloatField(blank=True, null=True, verbose_name='Individual course'),
        ),
    ]
