# Generated by Django 4.2.5 on 2023-12-24 14:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsitesCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='websites',
            name='description',
            field=models.CharField(default='12345', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='authority',
            field=models.CharField(max_length=100, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='date_of_issue',
            field=models.DateField(verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='passport_number',
            field=models.CharField(max_length=100, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='passport_scan_1',
            field=models.FileField(blank=True, upload_to='documents', verbose_name='Фото первой страницы паспорта'),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='passport_scan_2',
            field=models.FileField(blank=True, upload_to='documents', verbose_name='Фото страницы с пропиской'),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='passport_video',
            field=models.FileField(blank=True, upload_to='videos', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='status',
            field=models.CharField(choices=[('request', 'Verification request'), ('pending', 'Verification pending'), ('verified', 'Verified'), ('rejected', 'Verification rejected')], default='request', max_length=100),
        ),
        migrations.AlterField(
            model_name='websites',
            name='payment_method',
            field=models.IntegerField(choices=[(0, 'On system page'), (1, 'JS popup')], default=0),
        ),
        migrations.AlterField(
            model_name='websites',
            name='verification_code',
            field=models.CharField(auto_created=uuid.uuid4, default=uuid.uuid4, max_length=64),
        ),
        migrations.AddField(
            model_name='websites',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.websitescategories'),
        ),
    ]
