# Generated by Django 4.2.5 on 2023-12-24 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_links_method_alter_links_network'),
        ('customer', '0032_websitescategories_websites_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardslimits',
            name='min_limit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='websites',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.websitescategories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='websites',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency', verbose_name='Валюта инвойса'),
        ),
        migrations.AlterField(
            model_name='websites',
            name='description',
            field=models.CharField(max_length=1024, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='websites',
            name='domain',
            field=models.CharField(max_length=128, verbose_name='Домен'),
        ),
        migrations.AlterField(
            model_name='websites',
            name='payment_method',
            field=models.IntegerField(choices=[(0, 'On system page'), (1, 'JS popup')], default=0, verbose_name='Метод платежей'),
        ),
        migrations.AlterField(
            model_name='websites',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Active'), (2, 'Rejected'), (3, 'Blocked')], default=0),
        ),
        migrations.AlterField(
            model_name='websites',
            name='verified',
            field=models.IntegerField(choices=[(0, 'Verification pending'), (1, 'Verified'), (2, 'Not verified'), (3, 'Verification rejected')], default=0),
        ),
    ]
