# Generated by Django 4.2.5 on 2023-12-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0033_cardslimits_min_limit_alter_websites_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardslimits',
            old_name='min_limit',
            new_name='input_min_limit',
        ),
        migrations.AddField(
            model_name='cardslimits',
            name='output_min_limit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
