# Generated by Django 4.2.5 on 2023-12-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0034_rename_min_limit_cardslimits_input_min_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='payment_details',
            field=models.CharField(max_length=19, verbose_name='Номер карты'),
        ),
    ]
