# Generated by Django 4.2.5 on 2023-12-25 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0035_alter_cards_payment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 14, 10, 49, 780269, tzinfo=datetime.timezone.utc)),
        ),
    ]
