# Generated by Django 4.2.5 on 2023-12-25 14:15

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0037_alter_request_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='expiry',
            field=models.DateField(auto_created=customer.models.default_expiry, default=customer.models.default_expiry),
        ),
    ]
