# Generated by Django 4.2.5 on 2023-12-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0039_alter_request_category_alter_request_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='trader_orders',
            new_name='trader_limit',
        ),
    ]
