# Generated by Django 4.2.5 on 2023-12-25 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0040_rename_trader_orders_settings_trader_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('fees_in', models.FloatField()),
                ('fees_out', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.merchantscategories'),
        ),
    ]
