# Generated by Django 4.2.5 on 2023-12-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0042_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='user_agent',
            field=models.CharField(max_length=1024),
        ),
    ]
