# Generated by Django 4.2.5 on 2023-12-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0044_wallet_customer_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='account_type',
            field=models.CharField(choices=[('MERCHANT', 'Merchant'), ('TRADER', 'Trader')], default='MERCHANT', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='site',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
