# Generated by Django 4.2.5 on 2024-01-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0045_request_account_type_alter_request_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='min_order_amount',
            field=models.IntegerField(default=5000, verbose_name='Минимальная сумма ордеров клиентов(РУБ)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='system_wallet_address',
            field=models.CharField(default='', max_length=40, verbose_name='Адрес системного кошелька'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='system_wallet_private_key',
            field=models.CharField(default='', max_length=1024, verbose_name='Приватный ключ чистемного кошелька'),
            preserve_default=False,
        ),
    ]
