# Generated by Django 4.2.5 on 2023-12-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='frozen',
            field=models.FloatField(default=0),
        ),
    ]
