# Generated by Django 4.2.5 on 2023-12-12 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staticdata',
            old_name='title_en',
            new_name='title_en_us',
        ),
        migrations.RenameField(
            model_name='staticdataitems',
            old_name='content_en',
            new_name='content_en_us',
        ),
        migrations.RenameField(
            model_name='staticdataitems',
            old_name='title_en',
            new_name='title_en_us',
        ),
        migrations.RemoveField(
            model_name='staticdata',
            name='title_tr',
        ),
        migrations.RemoveField(
            model_name='staticdataitems',
            name='content_tr',
        ),
        migrations.RemoveField(
            model_name='staticdataitems',
            name='title_tr',
        ),
    ]
