# Generated by Django 4.2.5 on 2023-11-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangedirection',
            options={'ordering': ('created',), 'verbose_name': 'Exchange direction', 'verbose_name_plural': 'Exchange directions'},
        ),
    ]
