# Generated by Django 4.2.5 on 2023-12-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_links_method_alter_links_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=128)),
                ('binance_in', models.FloatField(default=0)),
                ('binance_out', models.FloatField(default=0)),
                ('commex_in', models.FloatField(default=0)),
                ('commex_out', models.FloatField(default=0)),
                ('grantex_in', models.FloatField(default=0)),
                ('grantex_out', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'ParsingCourses',
                'db_table': 'currency_courses',
                'ordering': ('pair',),
            },
        ),
    ]
